apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
  labels:
    app: myntra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
        - name: myntra
          image: 371952811305.dkr.ecr.ap-south-1.amazonaws.com/b12:a40f5fb29a7b85e3f33b29816c3c9a78b88fb817
          ports:
            - containerPort: 3000
