apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
  labels:
    app: myntra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
        - name: myntra
          image: 371952811305.dkr.ecr.ap-south-1.amazonaws.com/b12:d8a443770c9bba6306caeeb537b0cb60300e66bb
          ports:
            - containerPort: 3000
