apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
  labels:
    app: myntra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
        - name: myntra
          image: 521744733303.dkr.ecr.ap-south-1.amazonaws.com/b12:635a8dc55a74291344b7a8cd4fde95566c09b08a
          ports:
            - containerPort: 3000
