apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
  labels:
    app: myntra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
        - name: myntra
          image: prashant6749/myntra:latest  # Will be updated by GitHub Actions or Argo CD Image Updater
          ports:
            - containerPort: 3000
