apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
  labels:
    app: myntra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
        - name: myntra
          image: 234299494388.dkr.ecr.ap-south-1.amazonaws.com/b11:f65f4efcf12be16fdeec0903fd367d2554b31296
          ports:
            - containerPort: 3000
