apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
  labels:
    app: myntra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
        - name: myntra
          image: 234299494388.dkr.ecr.ap-south-1.amazonaws.com/b11:97b8c997f1be0f3c39a0fc4a4e183cad82614f16
          ports:
            - containerPort: 3000
