apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
  labels:
    app: myntra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
        - name: myntra
          image: 371952811305.dkr.ecr.ap-south-1.amazonaws.com/b12:c189f7dea44493dfc7fb37455cd1c03a58983524
          ports:
            - containerPort: 3000
